default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: <%= ENV.fetch("DB_USER", "app") %>
  password: <%= ENV.fetch("DB_PASSWORD", "app") %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>
  schema_search_path: <%= ENV.fetch("SEQUENT_MIGRATION_SCHEMAS") { "public, view_schema, sequent_schema" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "lms_development") %>

test:
  <<: *default
  database: lms_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "lms_production") %>
