default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  schema_search_path: <%= ENV.fetch("SEQUENT_MIGRATION_SCHEMAS") { "public, view_schema, sequent_schema" } %>

development:
  <<: *default
  database: course_recommendation_system_development

test:
  <<: *default
  database: course_recommendation_system_test

production:
  <<: *default
  database: course_recommendation_system_production
  username: course_recommendation_system
  password: <%= ENV["COURSE_RECOMMENDATION_SYSTEM_DATABASE_PASSWORD"] %>
